apiVersion: v1
kind: PersistentVolume
metadata:
    name: prometheus-nfs-pv
    namespace: monitoring
spec:
    capacity:
       storage: 5Gi
    accessModes:
       - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: cfs
    csi:
      driver: com.tencent.cloud.csi.cfs
      volumeAttributes:
        host: 10.154.0.20
        path: /prometheus
      volumeHandle: cfs-gl948iuv
