apiVersion: v1
kind: PersistentVolume
metadata:
    name: grafana-data-pv
spec:
    capacity:
       storage: 500Mi
    accessModes:
       - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: cfs
    csi:
      driver: com.tencent.cloud.csi.cfs
      volumeAttributes:
        host: 10.0.2.8
        path: /grafana-pv
      volumeHandle: cfs-7a2p06ez
