apiVersion: v1
kind: PersistentVolume
metadata:
    name: grafana-nfs-pv
    namespace: monitoring
spec:
    capacity:
       storage: 5Gi
    accessModes:
       - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: nfs
    nfs:
       path: /data/kubernetes/grafana
       server: 172.30.0.208
